import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import NavBarCrud from "./components/NavBarCrud/NavBarCrud";


const montserrat = Montserrat({
  subsets: ["latin"],
  style: ["italic", "normal"],
  weight: ["400", "700"],
  variable: "--font-montserrat"
});

export const metadata: Metadata = {
  title: "Ivan Trejo - Soluciones Star test",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <NavBarCrud />
        {children}</body>
    </html>
  );
}
